@startuml
' !theme materia

title RAC Vehicle Quick Response Claim Flow

' :Navigate to [[https://agreeable-hill-03062d410.2.azurestaticapps.net/]];

start

:Obtain RAC vehicle insurance;

:RAC Creates a custom QR Code sticker;
note left: Policy identification number \n is embedeed into the QR Code.

:Policy holder places the sticker on their windscreen.;

:Accidents occurs;

switch (Are you at fault)
    case(Yes)
        #lightgreen :Scan the QR code from your phone;

        #lightgreen :Redirect to claim selection landing page;

        #lightgreen :Select claim type, redirect to claim page. \n User's policy holder id can be prepopulated.;

        #lightgreen: Fill out the remaining part of the claim form;

        #lightgreen: Finish;
    case (Also Yes)
        #orange :Call RAC!;
        stop
    case(No)
        :Keep driving safely;
        stop;
endswitch





stop

@enduml